### ISSUE TITLE
Crates.io is at version 1.0.1

### ISSUE THREAD

**Issue by pilotstew** [ajour/ajour#728] opened 2021-08-24 02:37 UTC
I'm running Arch Linux and would prefer to install via cargo. However cargo currently installs version 1.0.1 can this be updated?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software involved**
Please complete the following information:
 - OS: [e.g. "Windows 10"]
 - Ajour version: [e.g. "0.3.2"]
 - (if applicable) Addon name, flavor (classic or retail) and version:

**Additional context**

**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.

**Comment by casperstorm** [comment] 2021-08-25 06:50
Duplicate of https://github.com/ajour/ajour/issues/668.

**Closed by casperstorm** 2021-08-25 06:50 UTC
Labels: B - bug
