### ISSUE TITLE
Flavor should be recognized if `interface/addon` folder is missing

### ISSUE THREAD

**Issue by haasy** [ajour/ajour#528] opened 2021-02-05 23:31 UTC
**Describe the bug**
WoW Classic does not appear in the game version drop down after a fresh install. Only after the game has been launched one time and the `Interface/Addon` has been created does it show up in the drop down. It probably effects every other supported WoW version too.

**To Reproduce**
1. Install WoW Classic
2. Launch Ajour
3. Select Folder with the fresh WoW Classic install as WoW directory
4. Classic does not show up in the game version drop down

**Expected behavior**
Classic should show up immediately after a fresh install.

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.7.0
 - WoW Classic

**Comment by casperstorm** [comment] 2021-02-06 10:00
Hi @haasy,

This is actually not a bug. It's expected because of the way flavors are detected. We are looking for excatly `interface/addon` to be there, in order to validate a falvor. It happens in the following function, if you would like to take a look:

https://github.com/ajour/ajour/blob/1c057fdb5f1f02915219664220978af79551723f/crates/core/src/config/mod.rs#L61

I'll convert it into a feature request, because we could look at improving this case.

**Comment by casperstorm** [comment] 2021-02-09 15:46
This is now fixed in 0.7.1-rc.1. Thanks for reporting this.

**Closed by casperstorm** 2021-02-09 15:46 UTC
Labels: B - missing feature, C - waiting on maintainer, S - addons, S - config
