### ISSUE TITLE
[minor Bug][Classic ERA] addon with incorrect Source

### ISSUE THREAD

**Issue by Altoholic** [ajour/ajour#645] opened 2021-05-23 02:35 UTC
**Describe the bug**
"Movement Speed" addon have "unknow" source, despite having been installed via Ajour (via Curse).

**Expected behavior**
Source should be "CurseForge"

**Software involved**
 - OS: Windows 10
 - Ajour version: 1.2.0
 - Classic ERA

**Comment by casperstorm** [comment] 2021-05-23 11:29
I can reproduce it, ill take a look. Thanks for reporting, @Altoholic.

**Comment by tarkah** [comment] 2021-05-24 17:36
@Altoholic we've identified the underlying issue and are waiting for it to get fixed in the upstream API.

**Comment by casperstorm** [comment] 2021-05-24 21:33
Upstream issue is fixed, @Altoholic. Please check if the issue is fixed, otherwise reopen.
I've just confirmed it works on my end.

**Closed by casperstorm** 2021-05-24 21:33 UTC
Labels: B - bug, C - waiting on maintainer, S - addons

**Comment by Altoholic** [comment] 2021-05-25 00:21
Working as intended :)
