### ISSUE TITLE
Classic add-on installed from Curse identified as Retail add-on from WoWI

### ISSUE THREAD

**Issue by bloodstrike** [ajour/ajour#627] opened 2021-04-23 04:38 UTC
**Describe the bug**
Fishing Buddy (Classic) version 0.7.3 beta 10 from CurseForge is identified as retail Fishing Buddy and tries to update to 1.16 on WoWInterface

**To Reproduce**
1. Go to Catalog
2. Install 'Fishing Buddy (Classic)'
3. Go to 'My Addons'
4. Ajour wants to update Fishing Buddy to 1.16 retail.

**Expected behavior**
Ajour needs to know the difference between these addons so that they don't get overwritten with incorrect and incompatible versions.

**Software involved**
Please complete the following information:
 - OS: MacOS 11.2
 - Ajour version: 1.1.0
 - (if applicable) Addon name, flavor (classic or retail) and version: Fishing Buddy (Classic)

**Comment by fvilers** [comment] 2021-04-23 06:47
It also happened to me this morning with one of these addons:

![image](https://user-images.githubusercontent.com/1009621/115830370-7b4ce100-a410-11eb-8b37-fa09f7f60be3.png)

**Comment by casperstorm** [comment] 2021-04-23 07:01
We had API issues this morning, can both of you try again now? It just got resolved here 2 minutes ago.

**Comment by fvilers** [comment] 2021-04-23 07:02
How do you want us to retry ? Uninstall everything and reinstall ?

**Comment by casperstorm** [comment] 2021-04-23 07:05
It should be enough to just press refresh. Issue was that all hashes from Curse was not working because of API 😞

**Comment by fvilers** [comment] 2021-04-23 07:22
Not sure if the issue is resolved as I still have some UI errors when loading the game. I didn't had them yesterday but this might be caused by the addon code itself.

Is it normal to have some addon with a *.toc file containing `## Interface: 80200` ?

**Comment by casperstorm** [comment] 2021-04-23 08:51
> Is it normal to have some addon with a *.toc file containing `## Interface: 80200` ?

Well, that is up to the addon developer to choose what Interface they wanna target. It is not always they remember to update it however.

**Comment by fvilers** [comment] 2021-04-23 08:54
In fact, I thought that 80200 is like version 8.02.00 which is way too higher for WoW Classic (and would be causing issue).

**Comment by casperstorm** [comment] 2021-04-23 09:00
I just tested with Nova World Buffs as well, which is also now fixed so I assume it is working again.
Regarding `Interface` then these are the newest:
Burning Crusade: `20501`
Classic: `11306`
Retail: `90005 `

**Comment by bloodstrike** [comment] 2021-04-23 13:05
Looks like everything is working correctly and identifying the correct addons this morning. Thanks for looking into it so quickly

**Closed** 2021-04-23 13:27 UTC
Labels: B - bug
