### ISSUE TITLE
[Bug] TBC Addon installed from Curse gets matched to Retail version from WowInterface

### ISSUE THREAD

**Issue by Bananaman** [ajour/ajour#676] opened 2021-07-07 18:26 UTC
1. Install "Fishing Buddy (Classic)" from Curse Catalog
2. Refresh addons.
3. Ajour shows a Retail update from WowInterface, which breaks the addon if you install it... 😁

![image](https://user-images.githubusercontent.com/38923130/124810448-a354d680-df61-11eb-9f36-63c0f166ea19.png)

**Comment by JoshStrobl** [comment] 2021-07-07 18:49
Duplicate of #664

**Comment by casperstorm** [comment] 2021-07-08 07:17
Gonna continue this in #664, as @JoshStrobl points out.

**Closed by casperstorm** 2021-07-08 07:17 UTC
Labels: B - bug

**Comment by Bananaman** [comment] 2021-07-08 09:29
Weird, I read through open issues and did not see that one. Sorry. 🤔
