### ISSUE TITLE
Fishing Buddy (Classic) being identified as Fishing Buddy

### ISSUE THREAD

**Issue by bloodstrike** [ajour/ajour#664] opened 2021-06-26 21:22 UTC
**Describe the bug**
Fishing Buddy (Classic) v. 0.7.5.2 installed from Curse is being identified as Fishing Buddy for retail from WoWI and Ajour wants to update and replace the classic version with the retail version (v. 1.16.3). This will break the addon in game because the retail version and the classic version work very differently. This has happened before and I thought it was fixed.

**To Reproduce**
1. Go to Catalog
2. Search for Fishing Buddy from Curse
3. Install Fishing Buddy (Classic) v 0.7.5.2
4. Go to My Addons and refresh
5. Ajour wants to update Fishing Buddy to 1.16.3 from WoWI

**Expected behavior**
Ajour should be able to tell the difference between "Fishing Buddy (Classic)" and "Fishing Buddy" and not attempt to overwrite.

**Software involved**
Please complete the following information:
 - OS: MacOS 11.4
 - Ajour version: 1.2.0
 - Fishing Buddy (Classic)

**Comment by casperstorm** [comment] 2021-07-08 07:19
I just installed `Fishing Buddy (Classic)` for TBC, through the catalog from Curse. When refreshing, it is still correctly matched. Can you guys try again and make sure you are running Ajour 1.2.2?

<img width="827" alt="Screenshot 2021-07-08 at 09 17 15" src="https://user-images.githubusercontent.com/2248455/124879379-73dbb380-dfcd-11eb-960a-5425bc93a8de.png">

**Comment by bloodstrike** [comment] 2021-07-08 13:59
Refreshing My Addons didn't resolve the issue, but reinstalling Fishing Buddy (Classic) seems to have fixed it. Thanks for the update!

**Comment by Bananaman** [comment] 2021-07-08 16:45
@casperstorm

- Ajour 1.2.1: Refresh matches to WoWI.
- Ajour 1.2.2: Refresh matches to WoWI.

On 1.2.2, I now did this test:

- Delete the addon.
- Install Fishing Buddy Classic 0.7.5.5 again.
- Of course My Addons list shows it as Curse now, as expected after a fresh install.
- Refreshed addons.
- Still showing as curse.

So yes it's fixed. I'm assuming by this commit:

https://github.com/ajour/ajour/commit/93cadf1c461c2e7b267f75d60baba242d1fabf29

What is your theory about why a reinstall was needed? I first assumed that Ajour had deleted the multi-TOC files on my existing install and therefore failed to match. But I literally opened an Ajour Addons backup file from a day ago and I see FishingBuddy-BCC.toc in there.

But I do notice one difference.

- Old fishingbuddy install (the one that failed in Ajour 1.2.2): Fishingbuddy.toc = 90005, Fishingbuddy-bcc.toc = CORRUPT FILE which ONLY contains the ## Interface: 20501 line.... FB version = 1.16.5 (according to changes.txt)
- New fishingbuddy reinstall (which works in Ajour 1.2.2): Fishingbuddy.toc = 20501, Fishingbuddy-classic.toc = Interface: 11307, FB version = 0.7.5.5

So it seems like the issue was that Fishingbuddy was incorrectly packaged at Curse, with a BCC zip file that was actually retail?

**Comment by bloodstrike** [comment] 2021-07-08 21:27
So I closed this because it worked, right? I just reopened Ajour v 1.2.2 and Fishing Buddy (Classic) 0.7.5.5 from Curse is again trying to update to retail Fishing Buddy v 1.16.6. I have no idea.

**Comment by casperstorm** [comment] 2021-07-08 21:45
So there is definitely something fishy going on. Maybe even multiple things.
First of all, we noticed an incorrect reference in the .toc file pointing to the retail version:

```
## X-Curse-Project-ID: 15093
## X-WoWI-ID: 4239
```
However, I am a little unsure why Ajour tries to match using ids, and not hashing. That is something ill have to look into. Maybe @tarkah has something to tip in with as well. 

Ill continue the hunt, @bloodstrike.

**Comment by Bananaman** [comment] 2021-07-08 22:28
> So I closed this because it worked, right? I just reopened Ajour v 1.2.2 and Fishing Buddy (Classic) 0.7.5.5 from Curse is again trying to update to retail Fishing Buddy v 1.16.6. I have no idea. I know that curse forge was having some dns problems earlier. Perhaps this is a problem on curse's end?

Mysterious. Mine doesn't do that anymore, I just did another Refresh, still matches itself to the TBC version. I even did a full exit of Ajour 1.2.2, restarted Ajour, did Refresh, still matches to 0.7.5.5 from Curse for TBC.

**Comment by Bananaman** [comment] 2021-07-08 22:30
@casperstorm It's weird, my comment a moment ago shows that mine matches properly, despite the bad curse project ID. And yes, the TBC toc file should definitely have a different project ID for the classic project. This is a pretty common error that I see many addon authors making. But in my case, it still somehow properly matches itself to the TBC version. :)

**Comment by casperstorm** [comment] 2021-07-13 09:39
I can't reproduce it after 93cadf1.
@bloodstrike, can you verify that if you remove Fishing Buddy through Ajour, and also verify manually that there's no folders left and then reinstall it through Catalog as you did before it still happens?

**Comment by Bananaman** [comment] 2021-07-16 01:43
@casperstorm Just a small update: Still.... No problems. 😂

Ajour is working. Fishing Buddy needs a reinstall for anyone who still has mismatch. Ajour has literally zero issues matching as I went into detail about earlier.

So you can close this. 😉👌❤️

**Closed** 2021-07-16 04:19 UTC
Labels: B - bug, S - addons
